### ISSUE TITLE
[ Question ] What "type" of Multiplayer is supported?

### ISSUE THREAD

**Issue by ktg5** [AdrianCassar/Xenia-WebServices#20]
Unsure if this is the correct way of asking this question, but what I mean by "what type of multiplayer", I'm talking about multiplayer that would use quick matches or lobbies of players.

Reason why I'm asking this is because I'm trying to figure out why one of the games I'm testing isn't working, as it seems to just create a session for each player when matchmaking & nothing else -- doesn't seem to see or try to connect to another session to make a full lobby & start the game. But, this could possibly be an issue with the game itself & might need a "patch" (although I'm unsure how these "patches" work, but would like to make my own at some point for other games).
Hopefully this makes sense.

(Also, unsure why, but issues on the [Xenia Netplay client](https://github.com/AdrianCassar/xenia-canary) & [Game Compatibility](https://github.com/xenia-netplay/game-compatibility) are disabled -- might want to possibly enable those?)

**Comment by AdrianCassar** [comment]
Xbox Live multiplayer, this is usually referred to as player or ranked matches in many games.

The chances are likely issues with net-code emulation, which requires investigating and debugging with VS. It's unlikely to be a server side issue unless something is indicating otherwise. Your issue sounds similar to Crackdown 2 lobbies for example.

Yes issues are disabled on the netplay repo as it's WIP therefore, issues are expected instead report issues in the discord channel, and the game compatibility repo isn't really in-use/setup at the moment.

**Comment by ktg5** [comment]
Ah okay, that was all I had to ask -- thank you!
